inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-md
  - rubocop-performance
AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/ExampleWording:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
RSpec/ExampleLength:
  Enabled: false